### PR TITLE
Added unit test support.

### PR DESCRIPTION
**Pull request by kylevedder**

### CODE REVIEW

**Comment by kylevedder** [comment]
There is an issue with Travis CI setting up the `clang++` compiler build:
 - When using `clang++`, setting up `gtest` fails because CMake cannot find `clang++` set in the `CXX` variable ([build](https://travis-ci.com/ut-amrl/amrl_shared_lib/jobs/266353107))
 - When using `g++`, setting up `gtest` succeeds because CMake finds `g++` set in the `CXX` variable ([build](https://travis-ci.com/ut-amrl/amrl_shared_lib/jobs/266353108))

I do not know how to fix this problem.

**Comment by joydeep-b** [comment]
@kylevedder I have accumulated a large number of line collision tests from multiple projects, in different languages. Could you please include them?

Tests from C++:
```cpp
TEST(LineIntersection, Intersects) {
  {
    const Line<float> l(Vector2f(-1, 0), Vector2f(1, 0));
    const Vector2f p2(0, -1);
    const Vector2f p3(0, 1);
    Vector2f intersection(0, 0);
    ASSERT_TRUE(l.Intersection(p2, p3, &intersection));
    ASSERT_FLOAT_EQ(intersection.x(), 0);
    ASSERT_FLOAT_EQ(intersection.y(), 0);
  }
  {
    const Line<float> l(Vector2f(-1, -1), Vector2f(3, 3));
    const Vector2f p2(2, -5);
    const Vector2f p3(-2, 5);
    Vector2f intersection(0, 0);
    ASSERT_TRUE(l.Intersection(p2, p3, &intersection));
    ASSERT_FLOAT_EQ(intersection.x(), 0);
    ASSERT_FLOAT_EQ(intersection.y(), 0);
  }
  {
    const Line<float> l(Vector2f(-5, -5), Vector2f(5, -5));
    const Vector2f p2(0, -5.25);
    const Vector2f p3(4.99, -5);
    Vector2f intersection(0, 0);
    ASSERT_TRUE(l.Intersection(p2, p3, &intersection));
    ASSERT_FLOAT_EQ(intersection.x(), 4.99);
    ASSERT_FLOAT_EQ(intersection.y(), -5);
  }
}
```
Tests from EJS:

```javascript
let i = 0;

test('intersect test ' + (++i).toString(), function() {
      let p1 = new geometry.Point(1, 1);
      let p2 = new geometry.Point(2, 2);
      let p3 = new geometry.Point(3, 3);
      let p4 = new geometry.Point(6, 6);
      let l1 = new geometry.Line(p1, p2);
      let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === false);
});

test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(0, 0);
  let p2 = new geometry.Point(0, 5);
  let p3 = new geometry.Point(0, 5);
  let p4 = new geometry.Point(6, 6);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === true);
});



test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(0, 0);
  let p2 = new geometry.Point(0, 5);
  let p3 = new geometry.Point(0, 4);
  let p4 = new geometry.Point(0, 6);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === true);
});


test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(0, 0);
  let p2 = new geometry.Point(0, 5);
  let p3 = new geometry.Point(0, 5);
  let p4 = new geometry.Point(0, 6);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === false);
});

test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(0, 0);
  let p2 = new geometry.Point(2, 3);
  let p3 = new geometry.Point(4, 6);
  let p4 = new geometry.Point(6, 9);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === false);
});


test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(1, 1);
  let p2 = new geometry.Point(2, 2);
  let p3 = new geometry.Point(1, 1);
  let p4 = new geometry.Point(2, 2);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === true);
});

test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(1, 1);
  let p2 = new geometry.Point(2, 2);
  let p3 = new geometry.Point(2, 1);
  let p4 = new geometry.Point(3, 2);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === false);
});

test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(5, 0);
  let p2 = new geometry.Point(5, 10);
  let p3 = new geometry.Point(0, 5);
  let p4 = new geometry.Point(10, 5);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === true);
});

test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(5, 0);
  let p2 = new geometry.Point(5, 10);
  let p3 = new geometry.Point(50, 50);
  let p4 = new geometry.Point(60, 60);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === false);
});

test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(-1, -1);
  let p2 = new geometry.Point(1, 1);
  let p3 = new geometry.Point(-2, -2);
  let p4 = new geometry.Point(3, 3);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === true);
});

test('intersect test ' + (++i).toString(), function() {
  let p1 = new geometry.Point(0, 0);
  let p2 = new geometry.Point(0, 5);
  let p3 = new geometry.Point(1, 1);
  let p4 = new geometry.Point(5, 5);
  let l1 = new geometry.Line(p1, p2);
  let l2 = new geometry.Line(p3, p4);
  assert(geometry.intersects(l1, l2) === false);
});

test('intersect test ' + (++i).toString(), function() {
  let l1 = new geometry.Line(new geometry.Point(0, 0), new geometry.Point(0, 5));
  let l2 = new geometry.Line(new geometry.Point(0, 4), new geometry.Point(0, 10));
  assert(geometry.intersects(l1, l2) === true);
});

test('intersect test ' + (++i).toString(), function() {
  let l1 = new geometry.Line(new geometry.Point(10, 10), new geometry.Point(10, 10));
  let l2 = new geometry.Line(new geometry.Point(30, 4), new geometry.Point(30, 10));
  assert(geometry.intersects(l1, l2) === false);
});


test('intersect test ' + (++i).toString(), function() {
  let l1 = new geometry.Line(new geometry.Point(0, 200), new geometry.Point(300, 200));
  let l2 = new geometry.Line(new geometry.Point(100, 300), new geometry.Point(100, 200));
  assert(geometry.intersects(l1, l2) === false);
});
```

**Comment by kylevedder** [comment]
The last EJS unit test is wrong:

```
test('intersect test ' + (++i).toString(), function() {
  let l1 = new geometry.Line(new geometry.Point(0, 200), new geometry.Point(300, 200));
  let l2 = new geometry.Line(new geometry.Point(100, 300), new geometry.Point(100, 200));
  assert(geometry.intersects(l1, l2) === false);
});
```
There is one line, `l1`, from `(0, 200)` to `(300, 200)`, and another line, `l2`, from `(100, 200)` to `(100, 300)`.

`l2`'s point `(100, 200)` sits on the line `l1` from `(0, 200)` to `(300, 200)`, so there should be a collision. However, the assert expects no intersection.

**Comment by joydeep-b** [comment]
> The last EJS unit test is wrong:
> `l2`'s point `(100, 200)` sits on the line `l1` from `(0, 200)` to `(300, 200)`, so there should be a collision. However, the assert expects no intersection.

True. This arises from the ambiguity of the user's expectation: is "intersection" == "crossing" || "touching", or is "intersection" == "crossing"?

This shows up when, for example, a robot is allowed to touch an obstacle, but not drive through it.

The definition in your implementation is "intersection" == "crossing" || "touching", which is fine, as long as we document it. Could you please add that in the function documentation?

**Review by joydeep-b — APPROVED** [review]
Looks good to me. Feel free to squash and merge when ready.

**Comment by kylevedder** [comment]
Updated the function documentation to reflect that `"intersection" == "crossing" || "touching"`. In a future PR I would like to rename these functions and cleanup the comments so that they are standardized. There is no consistent naming convention and some of the interfaces are poor.

**Pull request merged**
