### PR TITLE
Bugfix: Use non-templated std::abs

### PR DESCRIPTION
**Pull request by elvout**
Fixes a clang-12 compilation error

Related: https://github.com/ut-amrl/graph_navigation/pull/41

### CODE REVIEW

**Comment by elvout** [comment]
clang-12 emits an error when compiling `graph_navigation` with libtorch. It seems that libtorch redefines `std::abs`, which causes an ambiguous call to `std::abs<T>`. Removing the template specification resolves the error (although I'm not exactly sure why).

Error
```text
In file included from /home/elvin/ut-amrl/graph_navigation/src/navigation/navigation.h:29:
In file included from /home/elvin/ut-amrl/graph_navigation/src/navigation/eight_connected_domain.h:41:
In file included from /home/elvin/ut-amrl/graph_navigation/src/vector_map/vector_map.h:26:
/home/elvin/ut-amrl/graph_navigation/src/shared/math/line2d.h:87:12: error: call to 'abs' is ambiguous
    return std::abs<T>(geometry::Perp(dir).dot(p - p0));
           ^~~~~~~~~~~
/home/elvin/ut-amrl/graph_navigation/src/navigation/graph_domain.h:206:33: note: in instantiation of member function 'geometry::Line<float>::Distance' requested here
      const float dist = e.edge.Distance(v);
                                ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/complex:623:5: note: candidate function [with _Tp = float]
    abs(const complex<_Tp>& __z) { return __complex_abs(__z.__rep()); }
    ^
/opt/libtorch/include/c10/util/complex.h:543:19: note: candidate function [with T = float]
C10_HOST_DEVICE T abs(const c10::complex<T>& z) {
                  ^
1 error generated.
```

File: /opt/libtorch/include/c10/util/complex.h
```c++
530   │ namespace std {
531   │ 
532   │ template <typename T>
533   │ constexpr T real(const c10::complex<T>& z) {
534   │   return z.real();
535   │ }
536   │ 
537   │ template <typename T>
538   │ constexpr T imag(const c10::complex<T>& z) {
539   │   return z.imag();
540   │ }
541   │ 
542   │ template <typename T>
543   │ C10_HOST_DEVICE T abs(const c10::complex<T>& z) {
544   │ #if defined(__CUDACC__) || defined(__HIPCC__)
545   │   return thrust::abs(
546   │       c10_internal::cuda101bug_cast_c10_complex_to_thrust_complex(z));
547   │ #else
548   │   return std::abs(static_cast<std::complex<T>>(z));
549   │ #endif
550   │ }
...
589   │ } // namespace std
```

**Comment by elvout** [comment]
This error is also reproducible with g++-9

Error:
```
In file included from /home/elvin/ut-amrl/graph_navigation/src/vector_map/vector_map.h:26,
                 from /home/elvin/ut-amrl/graph_navigation/src/navigation/eight_connected_domain.h:41,
                 from /home/elvin/ut-amrl/graph_navigation/src/navigation/navigation.h:29,
                 from /home/elvin/ut-amrl/graph_navigation/src/navigation/social_nav.h:21,
                 from /home/elvin/ut-amrl/graph_navigation/src/navigation/social_nav.cc:23:
/home/elvin/ut-amrl/graph_navigation/src/shared/math/line2d.h: In instantiation of ‘T geometry::Line<T>::Distance(const Vector2T&) const [with T = float; geometry::Line<T>::Vector2T = Eigen::Matrix<float, 2, 1>]’:
/home/elvin/ut-amrl/graph_navigation/src/navigation/graph_domain.h:206:43:   required from here
/home/elvin/ut-amrl/graph_navigation/src/shared/math/line2d.h:87:23: error: call of overloaded ‘abs<float>(Eigen::ScalarBinaryOpTraits<float, float, Eigen::internal::scalar_product_op<float, float> >::ReturnType)’ i
s ambiguous
   87 |     return std::abs<T>(geometry::Perp(dir).dot(p - p0));
      |            ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/libtorch/include/c10/util/complex.h:3,
                 from /opt/libtorch/include/c10/util/Half.h:15,
                 from /opt/libtorch/include/c10/core/ScalarType.h:5,
                 from /opt/libtorch/include/c10/core/StorageImpl.h:4,
                 from /opt/libtorch/include/c10/core/Storage.h:3,
                 from /opt/libtorch/include/c10/core/TensorImpl.h:8,
                 from /opt/libtorch/include/c10/core/GeneratorImpl.h:12,
                 from /opt/libtorch/include/ATen/core/Generator.h:22,
                 from /opt/libtorch/include/ATen/Context.h:4,
                 from /opt/libtorch/include/ATen/ATen.h:9,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/all.h:8,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /home/elvin/ut-amrl/graph_navigation/build/CMakeFiles/social_nav.dir/cmake_pch.hxx:5,
                 from <command-line>:
/usr/include/c++/9/complex:623:5: note: candidate: ‘_Tp std::abs(const std::complex<_Tp>&) [with _Tp = float]’
  623 |     abs(const complex<_Tp>& __z) { return __complex_abs(__z.__rep()); }
      |     ^~~
In file included from /opt/libtorch/include/c10/util/Half.h:15,
                 from /opt/libtorch/include/c10/core/ScalarType.h:5,
                 from /opt/libtorch/include/c10/core/StorageImpl.h:4,
                 from /opt/libtorch/include/c10/core/Storage.h:3,
                 from /opt/libtorch/include/c10/core/TensorImpl.h:8,
                 from /opt/libtorch/include/c10/core/GeneratorImpl.h:12,
                 from /opt/libtorch/include/ATen/core/Generator.h:22,
                 from /opt/libtorch/include/ATen/Context.h:4,
                 from /opt/libtorch/include/ATen/ATen.h:9,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/data.h:3,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/all.h:8,
                 from /opt/libtorch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /home/elvin/ut-amrl/graph_navigation/build/CMakeFiles/social_nav.dir/cmake_pch.hxx:5,
                 from <command-line>:
/opt/libtorch/include/c10/util/complex.h:543:19: note: candidate: ‘T std::abs(const c10::complex<U>&) [with T = float]’
  543 | C10_HOST_DEVICE T abs(const c10::complex<T>& z) {
      |                   ^~~
```

**Comment by joydeep-b** [comment]
Quick question: does the problem still occur if you include the pytorch headers last?
Since the affected library in our case is header-only, it would be processed before Pytorch mucked up the definition then.

**Comment by elvout** [comment]
Yes. It also occurs if I explicitly make `#include "math/line2d.h"` the first line in files that use torch.

**Comment by joydeep-b** [comment]
Okay, merged.

**Pull request merged**
